quest Lycan5LvBec begin
	state start begin
		when login begin
			cmdchat("lycany_oto_bec "..q.getcurrentquestindex())
		end
		when info or button begin
		pc . set_skill_group ( 1 ) 
		pc . clear_skill ( ) 
		char_log ( 0 , "CLEAR_SKILL" , "Ögretmen silindikten sonraki dogal yetenek." ) 
		--say_title ( "Ejderha Gücü eðitimini seçtin." ) 
--		say ( "Hoþgeldin!" ) 
		if not pc . is_clear_skill_group ( ) then 
		--say ( "Ders almayý seçtiðin için 4 yetenek puaný " ) 
		--say ( "kazandýn. Bu puanlarý dilediðin herhangi bir" ) 
		--say ( "yeteneðini geliþtirmek için kullabilirsin." ) 
		--say_title ( "Bilgi:" ) 
		--say_reward ( "4 yetenek puaný kazandýn." ) 
		--say ( "" )
		pc . set_skill_level ( 170 , 0 ) 
		pc . set_skill_level ( 171 , 0 ) 
		pc . set_skill_level ( 172 , 0 ) 
		pc . set_skill_level ( 173 , 0 ) 
		pc . set_skill_level ( 174 , 0 ) 
		pc . set_skill_level ( 175 , 0 )
		pc . set_skill_level ( 137 , 20 ) 
		pc . set_skill_level ( 138 , 20 ) 
		pc . set_skill_level ( 139 , 20 ) 
		pc . set_skill_level ( 131 , 10 ) 
		pc . set_skill_level ( 129 , 20 ) 
		pc . set_skill_level ( 128 , 20 ) 
		pc . set_skill_level ( 127 , 20 ) 
		pc . set_skill_level ( 126 , 20 ) 
		pc . set_skill_level ( 124 , 20 ) 
		pc . set_skill_level ( 121 , 20 ) 
		pc . set_skill_level ( 137 , 20 ) 
		pc . set_skill_level ( 138 , 20 ) 
		pc . set_skill_level ( 139 , 20 ) 
		pc . set_skill_level ( 140 , 20 ) 
		pc . set_skill_level ( 124 , 20 ) 
		pc . set_skill_level ( 131 , 20 ) 
		pc . set_skill_level ( 121 , 20 ) 
		pc . set_skill_level ( 129 , 20 ) 
		pc . set_skill_level ( 126 , 20 ) 
		pc . set_skill_level ( 127 , 20 ) 
		pc . set_skill_level ( 128 , 20 ) 
		pc . set_skill_level ( 130 , 20 )
		horse . unride ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( )
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( )  
		end
		end
	end
end